---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fiesta-gts
  namespace: default
  labels:
    app:  web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app:  web
    spec:
      containers:
      - name: fiesta-app
        image: "wessenstam/gts-fiesta:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fiesta-svc
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 32222
  selector:
    app: web